// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package handlers

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson11879514DecodeUrlShortenerInternalHandlers(in *jlexer.Lexer, out *ShortenBatchResponses) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ShortenBatchResponses, 0, 2)
			} else {
				*out = ShortenBatchResponses{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 ShortenBatchResponse
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11879514EncodeUrlShortenerInternalHandlers(out *jwriter.Writer, in ShortenBatchResponses) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenBatchResponses) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11879514EncodeUrlShortenerInternalHandlers(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenBatchResponses) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11879514EncodeUrlShortenerInternalHandlers(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenBatchResponses) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11879514DecodeUrlShortenerInternalHandlers(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenBatchResponses) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11879514DecodeUrlShortenerInternalHandlers(l, v)
}
func easyjson11879514DecodeUrlShortenerInternalHandlers1(in *jlexer.Lexer, out *ShortenBatchResponse) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlation_id":
			out.ID = string(in.String())
		case "short_url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11879514EncodeUrlShortenerInternalHandlers1(out *jwriter.Writer, in ShortenBatchResponse) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"short_url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenBatchResponse) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11879514EncodeUrlShortenerInternalHandlers1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenBatchResponse) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11879514EncodeUrlShortenerInternalHandlers1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenBatchResponse) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11879514DecodeUrlShortenerInternalHandlers1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenBatchResponse) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11879514DecodeUrlShortenerInternalHandlers1(l, v)
}
func easyjson11879514DecodeUrlShortenerInternalHandlers2(in *jlexer.Lexer, out *ShortenBatchRequests) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(ShortenBatchRequests, 0, 2)
			} else {
				*out = ShortenBatchRequests{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v4 ShortenBatchRequest
			(v4).UnmarshalEasyJSON(in)
			*out = append(*out, v4)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11879514EncodeUrlShortenerInternalHandlers2(out *jwriter.Writer, in ShortenBatchRequests) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v5, v6 := range in {
			if v5 > 0 {
				out.RawByte(',')
			}
			(v6).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenBatchRequests) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11879514EncodeUrlShortenerInternalHandlers2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenBatchRequests) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11879514EncodeUrlShortenerInternalHandlers2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenBatchRequests) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11879514DecodeUrlShortenerInternalHandlers2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenBatchRequests) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11879514DecodeUrlShortenerInternalHandlers2(l, v)
}
func easyjson11879514DecodeUrlShortenerInternalHandlers3(in *jlexer.Lexer, out *ShortenBatchRequest) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "correlation_id":
			out.ID = string(in.String())
		case "original_url":
			out.URL = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson11879514EncodeUrlShortenerInternalHandlers3(out *jwriter.Writer, in ShortenBatchRequest) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"correlation_id\":"
		out.RawString(prefix[1:])
		out.String(string(in.ID))
	}
	{
		const prefix string = ",\"original_url\":"
		out.RawString(prefix)
		out.String(string(in.URL))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v ShortenBatchRequest) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson11879514EncodeUrlShortenerInternalHandlers3(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v ShortenBatchRequest) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson11879514EncodeUrlShortenerInternalHandlers3(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *ShortenBatchRequest) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson11879514DecodeUrlShortenerInternalHandlers3(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *ShortenBatchRequest) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson11879514DecodeUrlShortenerInternalHandlers3(l, v)
}
